   Algoritmo "exec_L103 Cadastro pessoal"
   // exec 03 = corrija os algoritmos
   // L1 = Lista 1
   //Disciplina   : [Linguagem e Lógica de Programação]
   // Descrição   : Aqui você descreve o que o programa faz! (função)
   // Autor(a)    : Nome do(a) aluno(a)
   // Data atual  : 27/07/2025
   Var
   // Seção de Declarações das variáveis
              numero     : inteiro
              idade      : inteiro
              nome       : caracter
              endereco   : caracter
              cpf        : real
              Rg         : inteiro
              genero     : caracter
              dta_Nasc   : inteiro
   Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
                  escreva("Digite o seu Nome:")
                  leia(nome)
                  escreva("Digite a sua Idade:")
                  leia(idade)
                  escreva("Digite a sua Data de Nascimento:")
                  leia(dta_Nasc)
                  escreva("Digite o seu Endereço:")
                  leia(endereco)
                  escreva("Digite o seu CPF:")
                  leia(cpf)
                  escreva("Digite o seu Registro Geral:")
                  leia(Rg)
                  escreva("Digite o seu Gênero:")
                  leia(genero)
                  escreval("")
                  escreval("Todas as informações")
                  escreval("Nome:",nome)
                  escreval("idade:",idade)
                  escreval("data de nascimento:",dta_Nasc)
                  escreval("Endereço:",endereco)
                  escreval("CPF:",cpf)
                  escreval("RG:",Rg)
                  escreval("Gênero:",genero)






   Fimalgoritmo