Algoritmo "EXE01033107"
   // Disciplina   : [Linguagem e Lógica de Programação]
   // Professor   : jose carlos
   // Descrição   : Faça um algoritmo que leia dois números,
   // e escreva a sua soma e o seu produto.
   // Autor(a)    : victor adriano
   // Data atual  : 31/07/2025
Var

       N1,N2,soma,produto :   INTEIRO
Inicio


      escreva("informe seu primeiro Número:")
      leia(N1)
      escreva("informe seu segundo Número:")
      leia(N2)
      escreval("")
      soma <-(N1+N2)
      produto <-(N1*N2)
      escreval("mostre o Primeiro número:",N1)
      escreval("mostre o Segundo número:",N2)
      escreval("")
      escreval("O Resultado da Soma:",soma)
      escreval("O Resultado da produto:",produto)


Fimalgoritmo