Algoritmo "EXE4022307"
   // Disciplina   : [Linguagem e Lógica de Programação]
   // Professor   : Jose carlos
   // Descrição   :    Leia a nota de um aluno e mostre “Excelente desempenho”,
   // caso a nota seja maior que 9.
   // Autor(a)    : Victor Adriano
   // Data atual  : 23/07/2025
Var
   nota : real


Inicio
      escreva ("informe a nota: ")
      leia (nota)
      se (nota > 9) entao
      escreva (" Excelente desempenho ")

fimse
Fimalgoritmo