Algoritmo "EXE4032307"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jose Carlos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Victor Adriano
// Data atual  : 23/07/2025
Var
   quantidade : inteiro


Inicio
      escreva("informe a quantidade de produtos:")
      leia (quantidade)
      se (quantidade < 5) entao
      escreva (" Estoque Baixo")

 fimse
Fimalgoritmo