   Algoritmo "exec_011807"
   // Disciplina   : [Linguagem e Lógica de Programação]
   // Professor   : jose carlos
   // Descrição   : Cadastro de Cliente
   // Autor(a)    : Victor Adriano
   // Data atual  : 22/07/2025
Var
   nome:       caractere
   cpf:        real
   dtaNasc :   caractere
   endereco :  caractere
   telefone:   caractere
   celular:    caractere
   email:      caractere
   profissao:  caractere

Inicio
      escreva("Informe o nome: ")
      leia(nome)
      escreva("Informe o endereço: ")
      leia(endereco)
      escreva("Informe o cpf: ")
      leia(cpf)
      escreva("Informe Data de nascimento: ")
      leia(dtaNasc)
      escreva("Informe o Telefone: ")
      leia(telefone)
      escreva("Informe o Celular: ")
      leia(celular)
      escreva("Informe o email: ")
      leia(email)
      escreva("Informe a profissão: ")
      leia(profissao)


Fimalgoritmo