Algoritmo "exec_011807"
     // Disciplina   : [Linguagem e Lógica de Programação]
     // Função: cadastro de Cliente
     // Professor   :
     // Descrição   : Aqui você descreve o que o programa faz! (função)
     // Autor(a)    : Henrique Freitas dos Santos
     // Data atual  : 18/07/2025
   Var
     Nome:       caractere
     CPF:        real
     Dta_Nasc:   caractere
     Endereco:   caractere
     Telefone:   caractere
     Celular:    caractere
     Email:      caractere
     Profissao:  caractere

   Inicio
     escreva   ("Informe o nome: ")
     leia      (Nome)
     escreva   ("CPF: ")
     leia      (CPF)
     escreva   ("Data de nascimento: ")
     leia      (Dta_Nasc)
     escreva   ("Endereço: ")
     leia      (Endereco)
     escreva   ("Telefone: ")
     leia      (Telefone)
     escreva   ("Celular: ")
     leia      (Celular)
     escreva   ("Email: ")
     leia      (Email)
     escreva   ("Profissão: ")
     leia      (Profissao)
     escreval  ("")
     escreval  ("Dados do Cliente")
     escreval  ("")
     escreval  ("Nome: ", Nome)
     escreval  ("CPF: ", CPF)
     escreval  ("Data de nascimento: ", Dta_Nasc)
     escreval  ("Endereço: ", Endereco)
     escreval  ("telefone: ", telefone)
     escreval  ("Celular: ", Celular)
     escreval  ("Email: ", Email)
     escreval  ("Profissão: ", Profissao)
     
Fimalgoritmo