Algoritmo "L02103007"
   // Disciplina   : [Linguagem e Lógica de Programação]
   // Professor   : Antonio Carlos Nicolodi
   // Descrição   : 10.Faça um algoritmo para ler a base e a altura de um
   // triângulo. Em seguida, escreva a área do mesmo.
   //Área = ( Base * Altura ) / 2
   // Autor(a)    : Pedro Elias
   // Data atual  : 30/07/2025
   Var
   A,B,H:real


   Inicio
   escreva("Escreva a Base: ", B)
   leia(B)
   escreva("Escreva a Altura: ", H)
   leia(H)
   //calculo
   A<- (B*H)/2
   escreval("")
   escreval("Área do triangulo")
   escreval("A Área é: ", A)

Fimalgoritmo